### ISSUE TITLE
'See all projects' button does not work if you filter by theme (the homepage feed)

### ISSUE THREAD

**Issue by cherriewang** [maitsu/bugs#3]
**Environment:** Chrome desktop browser, using Mac Mini

**Steps to reproduce:**
1. On https://maitsu.co/home use the 'Pick a theme' drop down menu and select '3D'
2. Click on the 'See all projects' button underneath "There are no checkins in 3d yet."

**Expected result**
You return to the homefeed that shows all the projects

**Actual result**
Magikarp used splash..

**Additional thoughts**
Padding feels a little tight for the 'See all projects' button. Maybe more spacing above it would feel nicer?

**Comment by jedmund** [comment]
Fixed this in https://github.com/maitsu/maitsu-svelte/pull/155
