### ISSUE TITLE
New Project Titles are White

### ISSUE THREAD

**Issue by rennsport** [maitsu/bugs#4]
When creating a new project, the project title becomes white and hard to see.

Steps to reproduce:
1) Create new project
2) Make it a custom project
3) Enter title
4) Click off of title

![Screenshot 2023-12-17 at 9 43 24 PM](https://github.com/maitsu/bugs/assets/982325/d8423151-12fc-40d0-93d7-3e5103b07dc2)

**Comment by cherriewang** [comment]
“Your project’s name” currently lighter grey than the “Your project’s goal”, and also when you click in to edit the project name the text/field turns orangey-red. 

![PNG image](https://github.com/maitsu/bugs/assets/8815266/5af2eb04-5804-43ab-b424-cfe9bb6b1580)
![PNG image](https://github.com/maitsu/bugs/assets/8815266/166c8b22-04c4-420e-b7c1-c2c400a17524)
